# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 18:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('display_name', models.CharField(max_length=25)),
                ('avatar_url', models.URLField(default='http://i.imgur.com/3iMO8An.png')),
                ('background_url', models.URLField(blank=True, default='')),
                ('followers', models.ManyToManyField(related_name='_userprofile_followers_+', to='twotter.UserProfile')),
                ('following', models.ManyToManyField(related_name='_userprofile_following_+', to='twotter.UserProfile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tweet',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twotter.UserProfile'),
        ),
    ]
