# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 18:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('twotter', '0002_auto_20160428_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwotterProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('display_name', models.CharField(max_length=25)),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('background_url', models.URLField(blank=True, default='')),
                ('followers', models.ManyToManyField(blank=True, related_name='_twotterprofile_followers_+', to='twotter.TwotterProfile')),
                ('following', models.ManyToManyField(blank=True, related_name='_twotterprofile_following_+', to='twotter.TwotterProfile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='following',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='twoot',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twotter.TwotterProfile'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
