# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twotter', '0003_auto_20160428_1452'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twoot',
            old_name='user_profile',
            new_name='twotter_profile',
        ),
    ]
