# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twotter', '0004_auto_20160428_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='twotterprofile',
            name='favorite_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='twotterprofile',
            name='twoot_count',
            field=models.IntegerField(default=0),
        ),
    ]
