# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twotter', '0007_auto_20160428_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='twotterprofile',
            name='birthday',
            field=models.CharField(default='Not Set Yet', max_length=25),
        ),
        migrations.AddField(
            model_name='twotterprofile',
            name='description',
            field=models.CharField(default='Not Set Yet', max_length=50),
        ),
        migrations.AddField(
            model_name='twotterprofile',
            name='follower_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='twotterprofile',
            name='following_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='twotterprofile',
            name='location',
            field=models.CharField(default='Not Set Yet', max_length=25),
        ),
    ]
